name: Build and Test

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.26.0
      - run: git checkout main && git checkout $GITHUB_SHA
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm test
      - run: pnpm run check-format
      - run: pnpm run lint
      - name: Store build artifact
        uses: actions/upload-artifact@v3
        with:
          name: static-assets
          path: dist
  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Download static assets
        uses: actions/download-artifact@v3
        with:
          name: static-assets
      - uses: JustUtahCoders/baseplate-deploy-action@main
        with:
          baseplate-token: ${{ secrets.BASEPLATE_TOKEN }}
          microfrontend-name: "@convex/navbar"
          environment-name: dev
          upload-dir: dist
          entry-file: convex-navbar.js
  deploy-stage:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Download static assets
        uses: actions/download-artifact@v3
        with:
          name: static-assets
      - uses: JustUtahCoders/baseplate-deploy-action@main
        with:
          baseplate-token: ${{ secrets.BASEPLATE_TOKEN }}
          microfrontend-name: "@convex/navbar"
          environment-name: stage
          upload-dir: dist
          entry-file: convex-navbar.js
  deploy-prod:
    needs: deploy-stage
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Download static assets
        uses: actions/download-artifact@v3
        with:
          name: static-assets
      - uses: JustUtahCoders/baseplate-deploy-action@main
        with:
          baseplate-token: ${{ secrets.BASEPLATE_TOKEN }}
          microfrontend-name: "@convex/navbar"
          environment-name: prod
          upload-dir: dist
          entry-file: convex-navbar.js
