name: Build and Deploy

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.26.0
      - run: git checkout main && git checkout $GITHUB_SHA
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm test
      - run: pnpm run check-format
      - run: pnpm run lint
      - uses: JustUtahCoders/baseplate-deploy-action@experimental-fetch
        with:
          baseplate-token: ${{ secrets.BASEPLATE_TOKEN }}
          microfrontend-name: "@convex/navbar"
          environment-name: prod
          upload-dir: dist
          entry-file: convex-navbar.js
